[package]
name = "shooter-client"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
rand = "0.3.13"
clap = "1.4.0"
cobalt = { version = "0.5.3", path = "../../cobalt-rs" }
shared = { version = "0.1.0", path = "../shared" }
clock_ticks = "0.1.0"
allegro = "0.0.22"
allegro-sys = "0.0.22"
allegro_primitives = "0.0.22"
allegro_font = "0.0.22"

