[package]
name = "shooter-server"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
clap = "1.4.0"
cobalt = { version = "0.7.0", path = "../../cobalt-rs" }
shared = { version = "0.1.0", path = "../shared" }

