[package]
name = "shared"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>"]

[dependencies]
num = "*"
rand = "*"
cobalt = "0.5.0"
allegro = "0.0.22"
allegro_primitives = "0.0.22"

